### ISSUE TITLE
ERROR: Long poll failed [Status 401]

### ISSUE THREAD

**Issue by georgeedwards** [ARMmbed/mbed-connector-api-node-quickstart#5]
If I run `git clone`, then `npm i` and then `node app.js` in the directory, then I get the following output:

```
node app.js
mbed Device Connector Quickstart listening at http://localhost:8080
ERROR: Long poll failed [Status 401]
C:\Users\George\Source\Repos\mbed-connector-api-node-quickstart\app.js:36
      throw error;
      ^

Error: Request failed: [Status 401] <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 401 </title>
</head>
<body>
<h2>HTTP ERROR: 401</h2>
<p>Problem accessing /v2/endpoints. Reason:
<pre>    Unauthorized</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.8.v20160314</a><hr/>
</body>
</html>


null
    at Object.Utility.handleError (C:\Users\George\Source\Repos\mbed-connector-api-node-quickstart\node_modules\mbed-connector-api\lib\utility.js:62:13)
    at EventEmitter.mbedConnectorApi.requestCallback (C:\Users\George\Source\Repos\mbed-connector-api-node-quickstart\node_modules\mbed-connector-api\lib\common.js:103:15)
    at Request._callback (C:\Users\George\Source\Repos\mbed-connector-api-node-quickstart\node_modules\mbed-connector-api\lib\common.js:95:21)
    at Request.self.callback (C:\Users\George\Source\Repos\mbed-connector-api-node-quickstart\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\George\Source\Repos\mbed-connector-api-node-quickstart\node_modules\request\request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\George\Source\Repos\mbed-connector-api-node-quickstart\node_modules\request\request.js:969:12)
```

**Comment by georgeedwards** [comment]
Oh, this is just a rubbish error message if there is not Access Key Specified
